### ISSUE TITLE
player_modifiers.lua hard overwrites other bonuses

### ISSUE THREAD

**Issue by jacobwatkinsgit** [M3wM3w/ComfyFactorio#100]
player_modifiers.lua assigns the player modifiers, disregarding any bonuses from technology or other mods.

I wrote a patch to save the previous modifiers [for each player]. The last modifier is subtracted before the new modifier is added.

I'm new to using git, so I'm going to do a pull request and may screw it up.

Tested single-player, but I tried to get it right for multiplayer.

**Comment by jacobwatkinsgit** [comment]
_Very_ new to using git. Was hoping I could push the code and have it rejected/added to a one-pull branch.

https://pastebin.com/n5SYsmNZ

**Comment by M3wM3w** [comment]
will change it so the lua is only active in modes that use it

we can't just take any old values, because then you would get infinite stats if stats get lower and higher during the game

**Comment by jacobwatkinsgit** [comment]
I've been jumping around maps, and so far nothing broke. Currently using two 'quality-of-life' research mods, but it'd be up to you of course if you were to change anything. Thanks for replying. I could close or you could I guess?

**Comment by M3wM3w** [comment]
try with hunger module, some stat might increase infinitely?

**Comment by jacobwatkinsgit** [comment]
I have been. A note on that is if the player modifier were attempted to be forced negative anyway, there would be a pcall error... (normally) one can either force-set it, which overwrites other mods and tech bonuses (there is a reset_technology_bonuses() function, which half helps), or sets it relatively... which has the problem of what to do if we did try to set it negative.

For what I wrote, I don't apply or keep the most up-to-date modifier if we would go negative. That just discards modifications entirely until we _can_ apply something that doesn't break, then it subtracts the last _successful_ update. Doesn't keep another mod from breaking it, but it's been working consistently.

**Comment by jacobwatkinsgit** [comment]
I'm playing one of the hunger ones now actually. Will see what happens if I go down to starving and back up (have a bunch of stat upgrades though so it might not hit the negative case...). Will get a log print if it would, so there's that.

**Comment by jacobwatkinsgit** [comment]
Haha, speak of the devil, I wanted faster mining speed and probably broke something cause I changed a single value in rpg:
3891.012 Script @C:/Users/Jacob/AppData/Roaming/Factorio/temp/currently-playing/player_modifiers.lua:68: player_modifiers.lua: error, changing bonus would set value below 0 and make an error (bad value, no GUI update)
3891.012 Script @C:/Users/Jacob/AppData/Roaming/Factorio/temp/currently-playing/player_modifiers.lua:69: modifier: character_mining_speed_modifier current value: 0.505 last recorded change: 0.96 new change: 1.44

Strength 70 mining speed 150.5% (cave choppy with rpg)

**Comment by jacobwatkinsgit** [comment]
Found an interesting bug with Factorio. Because I subtract the modifier and add the new one, for inventory, it can trigger a sub-tick inventory change and dump items. Changed my thing to make the difference, and then see if "currentvalue" + difference <= 0. Only applying the difference stops it. I'll report it on the bug forums tonight or tomorrow. Thanks? I think?

**Comment by ETK03** [comment]
I don't think that is a bug, it might just be subtracting in one tick, then adding in the next, allowing the inventory to have time to drop the items.
