### ISSUE TITLE
Blue beach, wrong wave_defense lua breaks map

### ISSUE THREAD

**Issue by jacobwatkinsgit** [M3wM3w/ComfyFactorio#105]
11: local WD = require "modules.wave_defense.main"
This causes the error:
AppData/Roaming/Factorio/temp/currently-playing/utils/event_core.lua:33: ...ming/Factorio/temp/currently-playing/maps/blue_beach.lua:191: attempt to call field 'get_table' (a nil value)

I looked at scrapyard, cause I knew that one worked:
require "modules.wave_defense.main"
local WD = require "modules.wave_defense.table"

Edit: the level loads, but the enemies haven't come for me... (wave 7). Thought it would take a while, like with some of the other WD maps.

**Comment by M3wM3w** [comment]
Fixed
