### ISSUE TITLE
perpetual chugging from chunk generation

### ISSUE THREAD

**Issue by jacobwatkinsgit** [M3wM3w/ComfyFactorio#107]
I'm trying out deepjungle, and I'm running into a UPS issue I believe I had on some other maps:

About once a second, the game has a very long update tick, dropping ups to 50-55 and the game just start-stops because of it. I traced it to map_generator from the debug times, and then if show-detailed-info is on, I see the chunks are increasing about one a second. I just started the game (don't have any research done) and even when standing still, more and more chunks are requested. Currently it shows 64-70 chunks active, and more than a thousand in the debug info (it just says: "Chunks:")

By the time I finished writing this post and going back and forth to look at debug info, an additional 200 chunks were generated (from 1400 to 1600), and a total of 154,745 entities. My ram usage isn't increasing significantly, but the map is nearly unplayable.

Edit: I posted for help on the forum, because it turns out the base mod alone is enough to cause 1 chunk request per second. I don't think that's necessarily a bad thing, but combined with a mod that does a lot on chunk generation... the game constantly chugs. I'm hoping I can at least defer the loading until I visit new chunks / pollution gets there.

**Comment by M3wM3w** [comment]
Yes, this map isn't even a "jungle" anymore, it needs a rewrite.

**Comment by jacobwatkinsgit** [comment]
I've been playing a bit with noise expressions... I wouldn't have an idea on what would make a "good" one, but it definitely seems to be much faster than placing things in lua code. Unfortunately it gets loaded during the data stage, not freely in a scenario.

I did confirm that the chunk loading stopped, thank goodness. In a new game, it stops around ~2200 around the starting area, and with a bit of exploration, I was at 2800. If anyone else has an issue or asks, there's a number you can give for when it would stop : P
