### ISSUE TITLE
more_attacks.lua "Given entity doesn't exist anymore"

### ISSUE THREAD

**Issue by jacobwatkinsgit** [M3wM3w/ComfyFactorio#108]
> 4668.799 Script @C:/Users/Jacob/AppData/Roaming/Factorio/temp/currently-playing/utils/event_core.lua:33: Given entity doesn't exist anymore.
stack traceback:
	...Factorio/temp/currently-playing/modules/more_attacks.lua:55: in function 'send_biters'
	...Factorio/temp/currently-playing/modules/more_attacks.lua:98: in function <...Factorio/temp/currently-playing/modules/more_attacks.lua:85>
	[C]: in function 'pcall'
	...ing/Factorio/temp/currently-playing/utils/event_core.lua:31: in function 'call_handlers'
	...ing/Factorio/temp/currently-playing/utils/event_core.lua:68: in function <...ing/Factorio/temp/currently-playing/utils/event_core.lua:66>

This is stoneblock, more_attacks is a normal module for it.

I checked for invalid entities and then nil'ed them out of the "biters to send" table. I got viciously attacked by hundreds of biters. Don't know what else I was expecting :(

**Comment by M3wM3w** [comment]
might remove the module and replace with wave defense module
