### ISSUE TITLE
fish_defender_v1 references fish_defender files (missing map_intro)

### ISSUE THREAD

**Issue by jacobwatkinsgit** [M3wM3w/ComfyFactorio#118]
fish_defender_v1 fails to load because maps.fish_defender.map_intro is "missing". There are other require's that reference fish_defender, but since fish_defender has those, it silently succeeds even though that's (probably?) not what is intended

I can't tell if fish_defender_v1 is supposed to be an older or newer version of fish defender, so there's some confusion on my part.

**Comment by ETK03** [comment]
In the first part, try changing `require "maps.fish_defender.map_intro"` to `require "maps.fish_defender_v1.map_intro"`. Fish defender v1 is the old one, so it might be missing some things or broken.

**Comment by M3wM3w** [comment]
thanks for telling jacobwatkinsgit !
fixed it
