### ISSUE TITLE
Improve admin logs : readibility

### ISSUE THREAD

**Issue by Masamune0** [M3wM3w/ComfyFactorio#130]
Right now it is hard to read logs, it should be : 
=>Timestamp at each line
=>Filters by force
=>Filters by items (show belts, hide...)
=>Red line when pumps or critical items are picked up
=>Orange line when a new player (<3h) is doing anything

**Comment by Masamune0** [comment]
Ideas received from discord : 
instead of playername save only player index is smaller
save gametick
maybe a number for the type of action
so there can be a long history with little data needed
i think it saves a whole string right now xd

**Comment by ETK03** [comment]
Maybe we could add a command like /history (name) that would make it more readable.
