### ISSUE TITLE
Checking scoreboard in bb map with heavy mode on crashes the game

### ISSUE THREAD

**Issue by Masamune0** [M3wM3w/ComfyFactorio#132]
![image](https://user-images.githubusercontent.com/24266778/73604838-4f3d0a00-4597-11ea-9868-a56cc9f0e52f.png)

How to reproduce : 
=>Host a BB map
=>/toggle-heavy-mode
=>open scoreboard

**Comment by Gerkiz** [comment]
Closing, this is now fixed.
Thank you for reporting this issue!
