### ISSUE TITLE
No compatible version specified

### ISSUE THREAD

**Issue by llVIU** [M3wM3w/ComfyFactorio#171]
Can you please specify which factorio version is this compatible with

**Comment by hanakocz** [comment]
If not said otherwise, always the latest experimental.

**Comment by llVIU** [comment]
What you said makes no sense. When you download the zip, it just says ''comfyfactorio-master'' , it should be ''comfyfactorio-version 0.18-1'' or 0.18-2 or 0-18-3 etc

**Comment by Gerkiz** [comment]
I have updated our `README.md` that states what version we use.
