### ISSUE TITLE
Cave Miner Scenario crashes with Factorio 0.18.27 on multiplayer server

### ISSUE THREAD

**Issue by ChurchOrganist** [M3wM3w/ComfyFactorio#175]
This may affect other scenarios in your pack too but I haven't tested.

The scenario runs fine in Factorio 0.18.28 in single player.

But crashed on startup with 0.18.27 on my Servernetic server.

Unfortunately the log file has been overwritten, but I have the dump file if you would like access to it.

**Comment by Gerkiz** [comment]
This is now fixed.
We have been running the scenario for quite some time now.
