### ISSUE TITLE
Huge lags when walking through resources on the ground with full inventory and high reach bonus (magic stat)

### ISSUE THREAD

**Issue by wladekb** [M3wM3w/ComfyFactorio#190]
So it's getting more and more annoying for me that I need to pause my exploration (MultiDungeons scenario) when my inventory gets full, because otherwise everyone starts to get huge lags. One of the situations even led me to being disconnected.

I'd suggest to look for solutions in the following order:
* check if RPG mod can be optimized so it doesn't consume that much time when you have a lot of resources in your reach range and a full inventory (maybe a check for full inventory to disable auto pickup of resources from the ground, or just enable that bonus for 1 tick per second?)
* if the RPG system uses native Factorio features report that issue to wube and hope for an optimization?

**Comment by hanakocz** [comment]
If you drop items to ground, each item needs to find a free position to place itself. If you keep dropping ores on ground, the area around gets filled and each next items takes more time (searches bigger area) to find free position, especially with dungeons map that has many non-free tiles. 

Solution is to adopt system that works on mountain fortress - immediately kill player who keeps mining with full inventory, thus no ores would be dropped to ground and no lags made.

**Comment by wladekb** [comment]
The root cause of an issue is not about placing the ores (which happens once), but the automatic pickup (that is likely to happen every tick?). We just tested it on the server.

Moreover disabling the reach bonus in RPG settings doesn't reduce the automatic pickup bonus range to the base value, but only the manual pickup range (pressing 'f').

**Comment by Gerkiz** [comment]
> The root cause of an issue is not about placing the ores (which happens once), but the automatic pickup (that is likely to happen every tick?). We just tested it on the server.
> 
> Moreover disabling the reach bonus in RPG settings doesn't reduce the automatic pickup bonus range to the base value, but only the manual pickup range (pressing 'f').

I'll disable the automatic pickup bonus range also.

**Comment by Gerkiz** [comment]
Updated RPG to also disable the rest of reach bonuses.
