### ISSUE TITLE
tired dangeon

### ISSUE THREAD

**Issue by NNM42** [M3wM3w/ComfyFactorio#234]
Comfy master and 0.30.
Factorio 1.1.25

Arena bosses don't spawn.
Broken new rooms? https://imgur.com/a/XFIpWDW

**Comment by hanakocz** [comment]
Yes, the scenario does not work atm. I have update under works, maybe few days.

**Comment by hanakocz** [comment]
@NNM42 ,this now should be fixed, if you redownload the files from repository, and start new game, tiered dungeon should now work. If you find any unexpectable behaviour, check the logs, if it gives some error there, feel free to report it :)
