### ISSUE TITLE
Noticeable delay every 1.5-2 seconds

### ISSUE THREAD

**Issue by klugemonkey** [M3wM3w/ComfyFactorio#3]
Seem to be getting a noticeable/consistent delay every second or two on a clean install, with one user.  Server cpu and network is not taxed, is something in game happening on nth tick that could cause this?

**Comment by M3wM3w** [comment]
Could be the map chunk generation. You can use /c map_pregen(32) for certain maps.

**Comment by klugemonkey** [comment]
Seems to be happening even on lost desert.  Running locally, the FPS/UPS are noticeably dropped.
