### ISSUE TITLE
Spectator = Team 3

### ISSUE THREAD

**Issue by cl0wnt0wn** [M3wM3w/ComfyFactorio#32]
Suggestion - Instead of having to join Team North / South, then go to Spectator mode, change would be to have Spectator Mode as essentially a Team 3.
- Prevents abuse from going from Team N to Spectate then back to Team N
- Can lock teams & define who can Spectate vs. Team N/S
- Can more easily define Spectator abilities
Thanks!

**Comment by M3wM3w** [comment]
The Issue with this is, if a new player joins into a game, they can go spectate and look at how well each team is doing exactly and join the "winning team". So this is why you have to choose your team first and then be able to spectate if you wanted. The price for spectating currently is, that you can only join back your team after a minute has passed.

**Comment by M3wM3w** [comment]
Could add that if the team lock button is used, that spectating while inside a team is disabled.

**Comment by M3wM3w** [comment]
Also, using the locking button puts all players that don't have a team into spectator mode right now.

**Comment by wellczech** [comment]
Current spectating is fine as is. What would be useful is something like Shout-casting team or force. Once joined, they can't leave. In GUI they can switch vision to see both teams, only one chosen team or have full vision even beyond normal player vision, e.g to see biters coming even before players themselves.
Also it would be nice to have some production info in GUI when in Shout-casting team to be able to compare how is each team doing.

It would be very useful during events like this
https://www.twitch.tv/videos/417247046?t=03h54m44s

**Comment by Sir3lit** [comment]
If anything the spectators should have a radar of ~800 so they can see the whole map area, and not just what is revealed from the player radar
