### ISSUE TITLE
BiterBattlesV2: configuration file feature

### ISSUE THREAD

**Issue by wellczech** [M3wM3w/ComfyFactorio#33]
For hosting BiterBattles matches between Twitch Streamers, we modify scripts, it would be easier, if there was one configuration file, where we can toggle following:

- **Name of teams in GUI**, especially JOIN button. Defaults: south and north
- **Amount of chunks to generate before game start**. Now it takes about 10 minutes, which is fine, but big exploration causes lag during game. We can have game running before event to pre-generate lot of chunks.
- **Team balancing on/off**

**Comment by M3wM3w** [comment]
Added config.lua for customization options.
