### ISSUE TITLE
[using factorio 0.16.51] maps.biter_battles_v2.biter_battles_v2 ctd with error when starting game

### ISSUE THREAD

**Issue by ErnestUTN** [M3wM3w/ComfyFactorio#60]
![image](https://user-images.githubusercontent.com/8976434/62418954-1ce43b80-b64c-11e9-8043-6982b5330185.png)

Greetings

I uncommented the --require"maps.biter_battles_v2.biter_battles_v2" to use this map.
When starting the scenario the error in the image above fires up.
Unable to play the scenario.

Using factorio 0.16.51
EDIT: seems this version is not meant for 0.16x
heading-2 font is not existent in stable factorio

**Comment by ErnestUTN** [comment]
---- enable maps here ----
--require "maps.cave_choppy.cave_miner"
require"maps.biter_battles_v2.biter_battles_v2"
--require "maps.biter_battles.biter_battles"
--require "maps.fish_defender.fish_defender"
--require "maps.wave_of_death.WoD"
--require "maps.stone_maze.main"
--require "maps.cave_miner"
--require "maps.labyrinth"
--require "maps.junkyard"
--require "maps.spooky_forest"
--require "maps.mixed_railworld"
--require "maps.nightfall"
--require "maps.lost"
--require "maps.hedge_maze"
--require "maps.rivers"
--require "maps.atoll"
--require "maps.rainbow_road"
--require "maps.cratewood_forest"
--require "maps.choppy"
--require "maps.tank_battles"
--require "maps.spiral_troopers"
--require "maps.mountain_fortress"
--require "maps.stoneblock"
--require "maps.deep_jungle"
--require "maps.crossing"
--require "maps.anarchy"
--require "maps.spaghettorio"
--require "maps.blue_beach"
--require "maps.lost_desert"
--require "maps.cube"
--require "maps.empty_map"
--require "maps.custom_start"
-----------------------------

This is what I have in that section in the the control.lua

**Comment by ErnestUTN** [comment]
![image](https://user-images.githubusercontent.com/8976434/62418991-e5c25a00-b64c-11e9-9842-bedb8e195111.png)

**Comment by M3wM3w** [comment]
0.16 is not supported
