### ISSUE TITLE
How is the "Total Time" value in "player" saved?

### ISSUE THREAD

**Issue by guoguomiao** [M3wM3w/ComfyFactorio#87]
I found that "Total Time" can be saved on the server you are running.
I want to know how to save values in old maps and use values in new maps

Thank you.

**Comment by Gerkiz** [comment]
Hi,
We currently store the `total time played` in a database.
Earlier we had the `total time played` stored in files, that were written via `game.write_file`

If you are interested in manually saving the total time, then download [this](https://github.com/M3wM3w/ComfyFactorio/releases/tag/0.166). 
This zip file has all the files that you need.

**Comment by guoguomiao** [comment]
>>Play>>The game created by the scene does not record the total game time of each player.

What do I have to do to save and use the player's total game time?

**Comment by guoguomiao** [comment]
Hello
I want to know how to output `total time played` And update the data for the next game
Can you tell me how to do it? Thank you

**Comment by Gerkiz** [comment]
Closing as the solution to this issue is posted her:
[https://github.com/M3wM3w/ComfyFactorio/issues/87#issuecomment-549958316](url)
