### ISSUE TITLE
Not the best way to do probability tables

### ISSUE THREAD

**Issue by Klonan** [M3wM3w/ComfyFactorio#91]
https://github.com/M3wM3w/ComfyFactorio/blob/125423cca0d2005935b6d543f1df40d2d6d7d747/maps/biter_hatchery/raffle_tables.lua#L1

This is a horrible way to do probabilities (no offense)

This is the way I would recommend to do it:

```lua

function select_unit(units)

  local roll_max = 1
  for k, unit in pairs (units) do
      roll_max = roll_max + unit.probability
    end
  end

  local roll_value = math.random(roll_max)
  for k, unit in pairs (units) do
    roll_value = roll_value - unit.probability
    if (roll_value < 0) then
      return unit.name
    end
  end

end

--And the raffle table will just be like:

local raffle = 
{
  {name = "small-biter", probability = 50},
  {name = "medium-biter", probability = 20},
  {name = "big-biter", probability = 10},
}
```

**Comment by M3wM3w** [comment]
I am aware that this method exists.

**The question i have about it:**
Isn't this more CPU work, when used for rather small tables?
Rolling a name by just doing for example 
`name = raffle[math.random(1, #raffle)]`
seems like it is very little effort to calculate?
It occupies more memory, but saves a few calculations,
or am i getting something wrong here?

**It obviously is not suitable for big probability ranges!!**

**Comment by Klonan** [comment]
The amount of CPU usage is absolutely insignificant
