### ISSUE TITLE
Use force.play_sound

### ISSUE THREAD

**Issue by Klonan** [M3wM3w/ComfyFactorio#92]
https://github.com/M3wM3w/ComfyFactorio/blob/125423cca0d2005935b6d543f1df40d2d6d7d747/maps/biter_hatchery/main.lua#L257

You don't need to loop through all the players, you can just play a sound for a force:
https://lua-api.factorio.com/latest/LuaForce.html#LuaForce.play_sound

**Comment by M3wM3w** [comment]
thank you and done!
