### ISSUE TITLE
Super heavy function

### ISSUE THREAD

**Issue by Klonan** [M3wM3w/ComfyFactorio#93]
https://github.com/M3wM3w/ComfyFactorio/blob/125423cca0d2005935b6d543f1df40d2d6d7d747/maps/biter_hatchery/main.lua#L178

This is a pretty hefty function call, depending on your map size, and you will be doing it every 1200 ticks for every force

It would probably be smoother if you just kept track of new units when they are created, or just not worry about pre-existing biters

**Comment by M3wM3w** [comment]
Replaced with keeping track of the units in a table!
